# Q4

## Part A

In [3]:
"""
Please define the mentioned matrices and the operations

consider the bellow links:
https://numpy.org/doc/stable/reference/generated/numpy.transpose.html

https://numpy.org/doc/stable/reference/generated/numpy.dot.html

"""
import numpy as np
#make matrix m1 
m1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('m1 :',m1)
#transpose m1 and print it for check
m1_t=np.transpose(m1)
print('transpose m1:',m1_t)
#dot production of matrix and trnspose of it  
m1_dot=np.dot(m1_t,m1)
#inverse it with funcyion of numpy
m1_inv=np.linalg.inv(m1_dot)
temp=np.array([[1],[-1],[1]])
m2=np.dot(m1_t,temp)
m11=np.dot(m1_inv,m2)
ans=np.add(m11,m1)
#print result
print('result:',ans)


m1 : [[1 2 3]
 [4 5 6]
 [7 8 9]]
transpose m1: [[1 4 7]
 [2 5 8]
 [3 6 9]]
result: [[0.78125  1.78125  2.78125 ]
 [4.       5.       6.      ]
 [7.171875 8.171875 9.171875]]


## Part B

In [12]:
def window_sliding(A, B):

  """
  In this function you should implement the sliding window method

  Arguments:
    inputs:
      A: a matrix of 3*3 order for treating as the window
      B: a matrix of 5*5 order for treating as the input matrix
    outputs:
      res: resulting matrix of the sliding window 
  """
  # write function for compute answer of production AA with part of B 
  # and return it
  def calc_func(a,b):
    ans=0
    for i in range(3):
      for j in range(3):
        ans=ans+(a[i][j]*b[i][j])
    return ans

  #for make 3*3 array,
  #use zeros for build 3*3 array with amount of 0
  res =np.zeros((3,3))
  #size of fx A is 3 and size of fx B is 5 
  #this same for fy
  # for this reson we write num variable for show reason why use 3
  num=5-3+1
  for i in range(0,num):
    for j in range(0,3):
      res[i][j]+=calc_func(A,B[i:i+3,j:j+3])

  return res

In [13]:
#initialize A,B and call method for compute aanswer and show it
A =np.array([ [1,1,1], [1,-9,1], [1,1,1]])
B =np.array([[1,1,1,1,1], [1,2,2,2,1], [1,2,2,2,1], [1,2,2,2,1], [1,1,1,1,1]])
print(window_sliding(A, B))

[[-7. -5. -7.]
 [-5. -2. -5.]
 [-7. -5. -7.]]
